#include "ar_letter_definitions.h"

namespace RDI
{

extern const std::vector<wchar_t> arabic_letters_with_tashkeel =
{
	HAMZA           ,
	ALEF_MADDA      ,
	ALEF_HAMZA_ABOVE,
	WAW_HAMZA_ABOVE ,
	ALEF_HAMZA_BELOW,
	YEH_HAMZA_ABOVE ,
	ALEF_NO_HAMZA   ,
	BEH             ,
	TEH_MARBOOTA    ,
	TEH             ,
	THEH            ,
	JEEM            ,
	HAH             ,
	KHAH            ,
	DAL             ,
	THAL            ,
	REH             ,
	ZAIN            ,
	SEEN            ,
	SHEEN           ,
	SAD             ,
	DAD             ,
	TAH             ,
	ZAH             ,
	AIN             ,
	GHAIN           ,
	FEH             ,
	QAF             ,
	KAF             ,
	LAM             ,
	MEEM            ,
	NOON            ,
	HEH             ,
	WAW             ,
	YEH_NO_DOTS     ,
	YEH_WITH_DOTS   ,
	TATWEEL         ,
	TANWEEN_FATHA   ,
	TANWEEN_DAMA    ,
	TANWEEN_KASRA   ,
	FATHA           ,
	DAMA            ,
	KASRA           ,
	SHADA           ,
	SKOON
};

extern const std::vector<wchar_t> arabic_letters_without_tashkeel =
{
	HAMZA           ,
	ALEF_MADDA      ,
	ALEF_HAMZA_ABOVE,
	WAW_HAMZA_ABOVE ,
	ALEF_HAMZA_BELOW,
	YEH_HAMZA_ABOVE ,
	ALEF_NO_HAMZA   ,
	BEH             ,
	TEH_MARBOOTA    ,
	TEH             ,
	THEH            ,
	JEEM            ,
	HAH             ,
	KHAH            ,
	DAL             ,
	THAL            ,
	REH             ,
	ZAIN            ,
	SEEN            ,
	SHEEN           ,
	SAD             ,
	DAD             ,
	TAH             ,
	ZAH             ,
	AIN             ,
	GHAIN           ,
	FEH             ,
	QAF             ,
	KAF             ,
	LAM             ,
	MEEM            ,
	NOON            ,
	HEH             ,
	WAW             ,
	YEH_NO_DOTS     ,
	YEH_WITH_DOTS
};

extern const std::vector<std::wstring> s_arabic_letters_with_tashkeel =
{
	S_HAMZA           ,
	S_ALEF_MADDA      ,
	S_ALEF_HAMZA_ABOVE,
	S_WAW_HAMZA_ABOVE ,
	S_ALEF_HAMZA_BELOW,
	S_YEH_HAMZA_ABOVE ,
	S_ALEF_NO_HAMZA   ,
	S_BEH             ,
	S_TEH_MARBOOTA    ,
	S_TEH             ,
	S_THEH            ,
	S_JEEM            ,
	S_HAH             ,
	S_KHAH            ,
	S_DAL             ,
	S_THAL            ,
	S_REH             ,
	S_ZAIN            ,
	S_SEEN            ,
	S_SHEEN           ,
	S_SAD             ,
	S_DAD             ,
	S_TAH             ,
	S_ZAH             ,
	S_AIN             ,
	S_GHAIN           ,
	S_FEH             ,
	S_QAF             ,
	S_KAF             ,
	S_LAM             ,
	S_MEEM            ,
	S_NOON            ,
	S_HEH             ,
	S_WAW             ,
	S_YEH_NO_DOTS     ,
	S_YEH_WITH_DOTS   ,
	S_TATWEEL         ,
	S_TANWEEN_FATHA   ,
	S_TANWEEN_DAMA    ,
	S_TANWEEN_KASRA   ,
	S_FATHA           ,
	S_DAMA            ,
	S_KASRA           ,
	S_SHADA           ,
	S_SKOON
};

extern const std::vector<std::wstring> s_arabic_letters_without_tashkeel =
{
	S_HAMZA           ,
	S_ALEF_MADDA      ,
	S_ALEF_HAMZA_ABOVE,
	S_WAW_HAMZA_ABOVE ,
	S_ALEF_HAMZA_BELOW,
	S_YEH_HAMZA_ABOVE ,
	S_ALEF_NO_HAMZA   ,
	S_BEH             ,
	S_TEH_MARBOOTA    ,
	S_TEH             ,
	S_THEH            ,
	S_JEEM            ,
	S_HAH             ,
	S_KHAH            ,
	S_DAL             ,
	S_THAL            ,
	S_REH             ,
	S_ZAIN            ,
	S_SEEN            ,
	S_SHEEN           ,
	S_SAD             ,
	S_DAD             ,
	S_TAH             ,
	S_ZAH             ,
	S_AIN             ,
	S_GHAIN           ,
	S_FEH             ,
	S_QAF             ,
	S_KAF             ,
	S_LAM             ,
	S_MEEM            ,
	S_NOON            ,
	S_HEH             ,
	S_WAW             ,
	S_YEH_NO_DOTS     ,
	S_YEH_WITH_DOTS
};

}
